# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cost_bernoullicpp <- function(v) {
    .Call(`_CDFmethod_cost_bernoullicpp`, v)
}

onechangeOPcpp <- function(data) {
    .Call(`_CDFmethod_onechangeOPcpp`, data)
}

myOPcpp <- function(data) {
    .Call(`_CDFmethod_myOPcpp`, data)
}

myPELTcpp <- function(data) {
    .Call(`_CDFmethod_myPELTcpp`, data)
}

onechangePELTcpp <- function(data) {
    .Call(`_CDFmethod_onechangePELTcpp`, data)
}

rcpp_hello_world <- function() {
    .Call(`_CDFmethod_rcpp_hello_world`)
}

